"""
KYC Document Storage
Handles secure file storage with presigned URLs pattern

Security model
--------------
* File references are generated by the server only and have a fixed shape
  (``documents/<user_id>/<name>`` or ``selfies/<user_id>/<name>``). Anything
  else -- absolute paths, ``..``, NULs, backslashes, extra segments -- is
  rejected before a path is ever built, and the final path is resolved and
  verified to be inside the storage root.
* Upload URLs carry a full-length HMAC-SHA256 signature bound to the user id,
  the HTTP method, the file reference and the expiry. The signature is an
  *additional* check: the API endpoints also require an authenticated user.
* Content is validated by size and magic bytes (JPEG / PNG / PDF) and is
  encrypted at rest (Fernet, key derived from ``KYC_ENCRYPTION_KEY``). Files
  stored before encryption was introduced are plaintext and stay readable.
"""
import os
import re
import uuid
import hmac
import hashlib
import logging
import tempfile
import time
from pathlib import Path
from typing import List, Optional, Tuple
from datetime import datetime

from app.core.kyc_encryption import (
    KYCConfigError,
    _is_production,
    decrypt_file_bytes,
    encrypt_file_bytes,
)

logger = logging.getLogger(__name__)

# Storage configuration
KYC_UPLOAD_DIR = Path(
    os.getenv("KYC_UPLOAD_DIR")
    or (Path(__file__).parent.parent.parent / "data" / "kyc_uploads")
)
ALLOWED_EXTENSIONS = {"jpg", "jpeg", "png", "pdf"}
IMAGE_EXTENSIONS = {"jpg", "jpeg", "png"}
MAX_FILE_SIZE = 10 * 1024 * 1024  # 10 MB
UPLOAD_URL_TTL_SECONDS = 3600  # 1 hour

CONTENT_TYPES = {
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "png": "image/png",
    "pdf": "application/pdf",
}

ENV_URL_SECRET = "KYC_URL_SECRET"
# Development-only fallback (public: it is in the repository). Refused in production.
_DEV_URL_SECRET = "kyc-url-signing-secret-dev"
_PLACEHOLDER_URL_SECRETS = frozenset({
    _DEV_URL_SECRET,
    "CHANGE_ME_BEFORE_PRODUCTION",
    "changeme",
})

# Both patterns are applied with ``fullmatch``: with ``match`` a trailing "$"
# would also accept a value that ends in a newline.
_SAFE_SEGMENT_RE = re.compile(r"[A-Za-z0-9_-]{1,64}")
# kind / owner user id / file name -- no dots, no separators, no NULs anywhere.
_FILE_REF_RE = re.compile(r"(documents|selfies)/([A-Za-z0-9_-]{1,64})/([A-Za-z0-9_-]{1,160})")


class InvalidFileRef(ValueError):
    """The file reference is not one this server could have generated."""


# ----------------------------------------------------------------------------
# Secrets
# ----------------------------------------------------------------------------

def _signing_secret() -> bytes:
    """Secret for signing upload URLs.

    Production: ``KYC_URL_SECRET`` is mandatory and must not be a default.
    Elsewhere: ``KYC_URL_SECRET`` if set, else derived from ``SECRET_KEY``,
    else the development default.
    """
    secret = (os.getenv(ENV_URL_SECRET) or "").strip()
    if _is_production():
        if not secret or secret in _PLACEHOLDER_URL_SECRETS:
            raise KYCConfigError(
                f"{ENV_URL_SECRET} is required in production and must not be a default/placeholder value. "
                "Set a long random value (e.g. `openssl rand -hex 32`)."
            )
        return secret.encode()
    if secret:
        return secret.encode()
    app_secret = (os.getenv("SECRET_KEY") or "").strip()
    if app_secret:
        return hmac.new(app_secret.encode(), b"kyc-url-signing-v2", hashlib.sha256).digest()
    return _DEV_URL_SECRET.encode()


def assert_kyc_storage_configured() -> None:
    """Raises ``KYCConfigError`` in production when the signing secret is missing/default."""
    _signing_secret()


# ----------------------------------------------------------------------------
# File references and path containment
# ----------------------------------------------------------------------------

def parse_file_ref(file_ref: str) -> Tuple[str, str, str]:
    """Validate a file reference and return ``(kind, owner_user_id, name)``.

    Raises ``InvalidFileRef`` for anything that is not a server-shaped ref.
    """
    if not isinstance(file_ref, str) or "\x00" in file_ref:
        raise InvalidFileRef("Invalid file reference")
    match = _FILE_REF_RE.fullmatch(file_ref)
    if not match:
        raise InvalidFileRef("Invalid file reference")
    return match.group(1), match.group(2), match.group(3)


def is_valid_file_ref(file_ref: str) -> bool:
    try:
        parse_file_ref(file_ref)
        return True
    except InvalidFileRef:
        return False


def file_ref_owner(file_ref: str) -> Optional[str]:
    """The user id embedded in a file reference, or None if the ref is invalid."""
    try:
        return parse_file_ref(file_ref)[1]
    except InvalidFileRef:
        return None


def file_ref_belongs_to(file_ref: str, user_id: str) -> bool:
    owner = file_ref_owner(file_ref)
    return owner is not None and isinstance(user_id, str) and hmac.compare_digest(owner, user_id)


def _storage_root() -> Path:
    return Path(KYC_UPLOAD_DIR).resolve()


def _resolve_storage_path(file_ref: str, extension: str) -> Path:
    """Build the on-disk path for a ref and prove it is inside the storage root."""
    parse_file_ref(file_ref)
    ext = (extension or "").lower()
    if ext not in ALLOWED_EXTENSIONS:
        raise InvalidFileRef("Invalid file extension")
    root = _storage_root()
    candidate = (root / f"{file_ref}.{ext}").resolve()
    if candidate == root or not candidate.is_relative_to(root):
        raise InvalidFileRef("File reference escapes the storage root")
    return candidate


def ensure_upload_dir():
    """Ensure the upload directory exists"""
    root = Path(KYC_UPLOAD_DIR)
    root.mkdir(parents=True, exist_ok=True, mode=0o700)
    # Create subdirectories for organization
    (root / "documents").mkdir(exist_ok=True, mode=0o700)
    (root / "selfies").mkdir(exist_ok=True, mode=0o700)


# ----------------------------------------------------------------------------
# Content validation
# ----------------------------------------------------------------------------

def normalize_extension(extension: Optional[str]) -> Optional[str]:
    ext = (extension or "").strip().lower().lstrip(".")
    if ext == "jpeg":
        return "jpg"
    return ext or None


def validate_file_type(filename: str) -> bool:
    """Check if file extension is allowed"""
    ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
    return ext in ALLOWED_EXTENSIONS


def validate_file_size(size_bytes: int) -> bool:
    """Check if file size is within limit"""
    return 0 < size_bytes <= MAX_FILE_SIZE


def sniff_file_type(content: bytes) -> Optional[str]:
    """Detect the real file type from magic bytes. Returns 'jpg', 'png', 'pdf' or None."""
    head = bytes(content[:16])
    if head.startswith(b"\xff\xd8\xff"):
        return "jpg"
    if head.startswith(b"\x89PNG\r\n\x1a\n"):
        return "png"
    if head.startswith(b"%PDF-"):
        return "pdf"
    return None


def extension_for_content_type(content_type: Optional[str]) -> Optional[str]:
    """Map a declared Content-Type to an extension (None when not a known type)."""
    value = (content_type or "").split(";", 1)[0].strip().lower()
    return {
        "image/jpeg": "jpg",
        "image/jpg": "jpg",
        "image/pjpeg": "jpg",
        "image/png": "png",
        "application/pdf": "pdf",
    }.get(value)


# ----------------------------------------------------------------------------
# File reference generation and URL signing
# ----------------------------------------------------------------------------

def _require_safe_segment(value: str, what: str) -> str:
    if not isinstance(value, str) or not _SAFE_SEGMENT_RE.fullmatch(value):
        raise InvalidFileRef(f"Invalid {what}")
    return value


def generate_file_ref(user_id: str, doc_type: str, side: str = "front") -> str:
    """
    Generate a unique file reference/path.
    Format: documents/{user_id}/{doc_type}_{timestamp}_{uuid}_{side}
    """
    _require_safe_segment(user_id, "user id")
    _require_safe_segment(doc_type, "document type")
    if side not in ("front", "back"):
        raise InvalidFileRef("Invalid document side")
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    unique_id = uuid.uuid4().hex
    return f"documents/{user_id}/{doc_type}_{timestamp}_{unique_id}_{side}"


def generate_selfie_ref(user_id: str) -> str:
    """Generate a unique selfie file reference"""
    _require_safe_segment(user_id, "user id")
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    unique_id = uuid.uuid4().hex
    return f"selfies/{user_id}/selfie_{timestamp}_{unique_id}"


def document_ref_matches(file_ref: str, user_id: str, doc_type: str, side: str) -> bool:
    """True when ``file_ref`` is a document ref of this user for exactly this doc type and side."""
    try:
        kind, owner, name = parse_file_ref(file_ref)
    except InvalidFileRef:
        return False
    return (
        kind == "documents"
        and hmac.compare_digest(owner, user_id)
        and name.startswith(f"{doc_type}_")
        and name.endswith(f"_{side}")
    )


def is_selfie_ref(file_ref: str, user_id: str) -> bool:
    try:
        kind, owner, _name = parse_file_ref(file_ref)
    except InvalidFileRef:
        return False
    return kind == "selfies" and hmac.compare_digest(owner, user_id)


def _sign_url(method: str, user_id: str, file_ref: str, expires_at: int) -> str:
    """Create the HMAC-SHA256 signature (full length) for a URL.

    Bound to: HTTP method, user id, path (file ref) and expiry.
    """
    message = "\n".join(["kyc-url-v2", method.upper(), str(user_id), file_ref, str(int(expires_at))])
    return hmac.new(_signing_secret(), message.encode("utf-8"), hashlib.sha256).hexdigest()


def build_upload_url(user_id: str, file_ref: str) -> dict:
    """Signed PUT URL (plus metadata) for a server-generated file reference."""
    if not file_ref_belongs_to(file_ref, user_id):
        raise InvalidFileRef("File reference does not belong to this user")
    expires_at = int(time.time()) + UPLOAD_URL_TTL_SECONDS
    signature = _sign_url("PUT", user_id, file_ref, expires_at)
    return {
        "upload_url": f"/kyc/documents/upload/{file_ref}?expires={expires_at}&sig={signature}",
        "file_ref": file_ref,
        "expires_at": expires_at,
        "method": "PUT",
        "max_size_bytes": MAX_FILE_SIZE,
        "allowed_types": sorted({normalize_extension(e) for e in ALLOWED_EXTENSIONS}),
    }


def generate_upload_url(user_id: str, doc_type: str, side: str = "front") -> dict:
    """
    Generate a presigned upload URL (simulated for local storage).
    In production, this would generate an S3 presigned URL.

    Returns:
        dict with upload_url, file_ref, expires_at
    """
    ensure_upload_dir()
    file_ref = generate_file_ref(user_id, doc_type, side)
    return build_upload_url(user_id, file_ref)


def verify_upload_signature(user_id: str, file_ref: str, expires_at: int, signature: str) -> bool:
    """Verify the signature on an upload URL for this user, method PUT, path and expiry."""
    try:
        expires_at = int(expires_at)
    except (TypeError, ValueError):
        return False
    now = time.time()
    if now > expires_at:
        return False
    # Never accept an expiry further out than this server would have issued.
    if expires_at > now + UPLOAD_URL_TTL_SECONDS + 60:
        return False
    if not isinstance(signature, str) or not file_ref_belongs_to(file_ref, user_id):
        return False
    expected_sig = _sign_url("PUT", user_id, file_ref, expires_at)
    return hmac.compare_digest(signature.encode("utf-8"), expected_sig.encode("utf-8"))


# ----------------------------------------------------------------------------
# Storage
# ----------------------------------------------------------------------------

def save_uploaded_file(
    file_ref: str,
    content: bytes,
    extension: Optional[str] = None,
    images_only: bool = False,
) -> Tuple[bool, str]:
    """
    Validate and save an uploaded file to storage (encrypted at rest).

    ``extension`` is the type the client *declared* (optional). The stored
    type always comes from the content's magic bytes; a declared type that
    disagrees with the content is rejected.

    Returns:
        Tuple of (success, detected_extension or error_message)
    """
    try:
        parse_file_ref(file_ref)
    except InvalidFileRef:
        return False, "Invalid file reference"

    if not content:
        return False, "Empty file content"
    if not validate_file_size(len(content)):
        return False, f"File too large. Max size: {MAX_FILE_SIZE // 1024 // 1024}MB"

    detected = sniff_file_type(content)
    if detected is None:
        return False, "Unsupported file content. Upload a JPG, PNG or PDF file"

    declared = normalize_extension(extension)
    if declared is not None:
        if declared not in {normalize_extension(e) for e in ALLOWED_EXTENSIONS}:
            return False, "Invalid file type. Allowed: JPG, PNG, PDF"
        if declared != detected:
            return False, "File content does not match its declared type"

    if images_only and detected not in IMAGE_EXTENSIONS:
        return False, "Invalid file type. Allowed: JPG, PNG"

    ensure_upload_dir()
    try:
        file_path = _resolve_storage_path(file_ref, detected)
    except InvalidFileRef:
        return False, "Invalid file reference"

    tmp_name = None
    try:
        file_path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        encrypted = encrypt_file_bytes(bytes(content))
        fd, tmp_name = tempfile.mkstemp(dir=str(file_path.parent), prefix=".upload-", suffix=".tmp")
        with os.fdopen(fd, "wb") as f:
            f.write(encrypted)
        os.chmod(tmp_name, 0o600)
        os.replace(tmp_name, file_path)
        tmp_name = None
    except KYCConfigError:
        raise
    except Exception as e:
        logger.error("Failed to save KYC file: %s", type(e).__name__)
        return False, "Failed to save file"
    finally:
        if tmp_name:
            try:
                os.unlink(tmp_name)
            except OSError:
                pass

    # One ref -> one file: drop a previous upload stored under another extension.
    for ext in ALLOWED_EXTENSIONS:
        if ext == detected:
            continue
        try:
            stale = _resolve_storage_path(file_ref, ext)
            if stale.is_file():
                stale.unlink()
        except (InvalidFileRef, OSError):
            continue

    return True, detected


def get_file_path(file_ref: str) -> Optional[Path]:
    """Get the full path to a stored file (None for unknown or invalid references)"""
    # Find file with any extension
    for ext in sorted(ALLOWED_EXTENSIONS):
        try:
            full_path = _resolve_storage_path(file_ref, ext)
        except InvalidFileRef:
            return None
        if full_path.is_file():
            return full_path
    return None


def file_exists(file_ref: str) -> bool:
    return get_file_path(file_ref) is not None


def stored_file_extension(file_ref: str) -> Optional[str]:
    """Normalized extension ('jpg', 'png', 'pdf') of the stored file, or None."""
    path = get_file_path(file_ref)
    if not path:
        return None
    return normalize_extension(path.suffix)


def read_stored_file(file_ref: str) -> Optional[Tuple[bytes, str]]:
    """Read and decrypt a stored file.

    Returns ``(content, content_type)`` or None when the file does not exist.
    Legacy plaintext files are returned unchanged.
    """
    path = get_file_path(file_ref)
    if not path:
        return None
    with open(path, "rb") as f:
        blob = f.read()
    content = decrypt_file_bytes(blob)
    detected = sniff_file_type(content) or normalize_extension(path.suffix)
    return content, CONTENT_TYPES.get(detected or "", "application/octet-stream")


def list_user_document_files(user_id: str) -> List[Tuple[str, float]]:
    """``(file_ref, modified_at)`` for every document file stored for ``user_id``.

    Read from the storage directory, so it also finds files that were uploaded
    but never confirmed (those are recorded nowhere else). Selfies and
    in-progress temporary files are not included.
    """
    try:
        _require_safe_segment(user_id, "user id")
    except InvalidFileRef:
        return []
    root = _storage_root()
    directory = (root / "documents" / user_id).resolve()
    if not directory.is_relative_to(root) or not directory.is_dir():
        return []
    found: List[Tuple[str, float]] = []
    try:
        entries = list(directory.iterdir())
    except OSError:
        return []
    for entry in entries:
        if entry.suffix.lstrip(".").lower() not in ALLOWED_EXTENSIONS:
            continue
        file_ref = f"documents/{user_id}/{entry.stem}"
        if not is_valid_file_ref(file_ref):
            continue
        try:
            if not entry.is_file():
                continue
            found.append((file_ref, entry.stat().st_mtime))
        except OSError:
            continue
    return found


def delete_file(file_ref: str) -> bool:
    """Delete a file from storage"""
    file_path = get_file_path(file_ref)
    if file_path and file_path.exists():
        try:
            file_path.unlink()
            return True
        except OSError:
            return False
    return False
