import sqlite3, json, datetime
c=sqlite3.connect(r'backends/shared/shared_lib/persistence/cosmicforge.db', timeout=5); c.row_factory=sqlite3.Row
q=lambda s,p=(): c.execute(s,p).fetchone()[0]
rs=lambda s,p=(): [dict(x) for x in c.execute(s,p)]
now=datetime.datetime.now(datetime.timezone.utc); cut=(now-datetime.timedelta(hours=24)).isoformat()
tables=['economic_events','event_blackout_windows','decision_traces','raw_news_items','news_clusters','news_intelligence_signals','news_provider_health','event_market_snapshots','market_event_reactions','news_market_reactions','narrative_effectiveness_scores']
o={'time':now.isoformat(),'counts':{t:q(f'SELECT COUNT(*) FROM {t}') for t in tables}}
o['events']={'latest':q('select max(scheduled_utc) from economic_events'),'active_blackouts':q('select count(*) from event_blackout_windows where is_active=1 and start_utc<=? and end_utc>=?',(now.isoformat(),now.isoformat())),'blocks':q('select count(*) from decision_traces where event_blocked=1'),'blocks_24h':q('select count(*) from decision_traces where event_blocked=1 and ts>=?',(cut,)),'blocked_in_windows':q('select count(*) from decision_traces d join event_blackout_windows w on d.ts between w.start_utc and w.end_utc where d.event_blocked=1'),'unblocked_in_windows':q('select count(*) from decision_traces d join event_blackout_windows w on d.ts between w.start_utc and w.end_utc where coalesce(d.event_blocked,0)=0')}
total=o['counts']['raw_news_items']; dup=q('select count(*) from raw_news_items where is_duplicate=1')
o['news']={'new_24h':q('select count(*) from raw_news_items where ingested_utc>=?',(cut,)),'latest':q('select max(ingested_utc) from raw_news_items'),'duplicates':dup,'duplicate_pct':100*dup/total if total else 0,'sentiment':rs('select coalesce(sentiment_label,signal_type) label,count(*) n from news_intelligence_signals group by 1 order by n desc'),'top_narratives':rs('select narrative_type,count(*) n from news_intelligence_signals group by narrative_type order by n desc limit 5'),'reliability':rs("select case when reliability_score>=.8 then 'HIGH' when reliability_score>=.5 then 'MEDIUM' else 'LOW' end band,count(*) n from news_intelligence_signals group by 1"),'invalid':q('select count(*) from news_intelligence_signals where coalesce(is_valid_signal,0)=0'),'low_conf':q("select count(*) from news_intelligence_signals where data_quality_status='LOW_CONFIDENCE' or confidence_score<0.5"),'manipulation':q("select count(*) from news_intelligence_signals where coalesce(manipulation_flag,'') not in ('','0','NONE','FALSE')"),'fake_risk':q('select count(*) from news_intelligence_signals where coalesce(fake_news_risk_score,0)>0'),'conflict':q('select count(*) from news_intelligence_signals where coalesce(conflict_flag,0)!=0'),'unsafe':q('select count(*) from news_intelligence_signals where shadow_only != 1 or should_affect_trading != 0')}
o['providers']={'latest':rs('select h.source_id,h.status,h.last_checked_utc,h.last_success_utc,h.error_message from news_provider_health h join (select source_id,max(id) id from news_provider_health group by source_id)x on h.id=x.id order by h.source_id'),'fail_24h':q("select count(*) from news_provider_health where created_at>=? and (upper(status) not in ('HEALTHY','OK','ACTIVE') or error_message is not null)",(cut,))}
nr=o['counts']['news_market_reactions']; false=q('select count(*) from news_market_reactions where is_false_signal=1')
o['reactions']={'latest_event_reaction':q('select max(created_at) from market_event_reactions'),'event_types':rs('select reaction_type,count(*) n from market_event_reactions group by reaction_type order by n desc'),'volatility':rs('select event_id,symbol,round(volatility_expansion_ratio,3) volatility_x,round(net_move_pct,3) net_move_pct from market_event_reactions where volatility_expansion_ratio is not null order by volatility_expansion_ratio desc limit 3'),'news_types':rs('select reaction_type,count(*) n from news_market_reactions group by reaction_type order by n desc'),'false_count':false,'false_pct':100*false/nr if nr else 0,'accuracy':rs('select sentiment_accuracy,count(*) n from news_market_reactions group by sentiment_accuracy order by n desc'),'narratives':rs('select narrative_type,sample_count,avg_impact_score,correct_sentiment_ratio,false_signal_ratio,avg_effectiveness_score from narrative_effectiveness_scores order by avg_effectiveness_score desc,narrative_type')}
print(json.dumps(o,indent=2))
