"""Research data contract and dataset tooling (Phase 14).

Kept separate from ``app.replay``: replay is about reproducing the *system*,
this is about the *data* the system is measured on. They meet only where a
replay is handed a dataset.
"""

from app.research.dataset import (
    FINAL_HOLDOUT,
    BROKER_DEMO,
    DEFAULT_TRAINING_PROVENANCE,
    FEATURE_SCHEMA_VERSION,
    LABEL_SCHEMA_VERSION,
    LEGACY_BACKFILL,
    LIVE,
    PAPER_FORWARD,
    REAL_HISTORICAL,
    REPLAY,
    RESEARCH_PROVENANCE,
    SYNTHETIC,
    TESTNET,
    TRAINING_EXAMPLE_SCHEMA_VERSION,
    DatasetError,
    DatasetManifest,
    FinalHoldoutViolation,
    FutureLabelSet,
    InstrumentIdentity,
    Partition,
    QualityReport,
    ResearchFeatureContext,
    TrainingExample,
    assess_quality,
    build_manifest,
    build_training_example,
    derive,
    filter_by_provenance,
    guard_final_holdout,
    include_for_training,
    partition,
)

__all__ = [
    "BROKER_DEMO",
    "DEFAULT_TRAINING_PROVENANCE",
    "DatasetError",
    "DatasetManifest",
    "FEATURE_SCHEMA_VERSION",
    "FINAL_HOLDOUT",
    "FinalHoldoutViolation",
    "FutureLabelSet",
    "InstrumentIdentity",
    "LABEL_SCHEMA_VERSION",
    "LEGACY_BACKFILL",
    "LIVE",
    "PAPER_FORWARD",
    "Partition",
    "QualityReport",
    "REAL_HISTORICAL",
    "REPLAY",
    "RESEARCH_PROVENANCE",
    "ResearchFeatureContext",
    "SYNTHETIC",
    "TESTNET",
    "TRAINING_EXAMPLE_SCHEMA_VERSION",
    "TrainingExample",
    "assess_quality",
    "build_manifest",
    "build_training_example",
    "derive",
    "filter_by_provenance",
    "guard_final_holdout",
    "include_for_training",
    "partition",
]
