from __future__ import annotations

STATUS_UPDATE_INTERVAL_MINUTES = 5
PAIR_DISCOVERY_INTERVAL_HOURS = 24
SIGNAL_GENERATION_TIMES_UTC = ["07:00", "12:00", "16:00", "20:00"]

DEFAULT_GENERATION_MODE = "tier_1_tier_2"
DEFAULT_ROLLOUT_MODE = "TIER_1_TIER_2"
ROLLOUT_V1_SEED_ONLY = "V1_SEED_ONLY"
ROLLOUT_TIER_1_ONLY = "TIER_1_ONLY"
ROLLOUT_TIER_1_TIER_2 = "TIER_1_TIER_2"
ROLLOUT_TIER_1_TIER_2_TIER_3 = "TIER_1_TIER_2_TIER_3"
ROLLOUT_MODES = {
    ROLLOUT_V1_SEED_ONLY,
    ROLLOUT_TIER_1_ONLY,
    ROLLOUT_TIER_1_TIER_2,
    ROLLOUT_TIER_1_TIER_2_TIER_3,
}

DEFAULT_MAX_SYMBOLS = 50
DEFAULT_MAX_PUBLISHED_PER_SCAN = 10
DEFAULT_MAX_ACTIVE_SIGNALS = 20
DEFAULT_MIN_VOLUME = 50_000_000
DEFAULT_MAX_SPREAD = 0.20
DEFAULT_TIERS = ["TIER_1", "TIER_2"]
TIER_3_ENABLED = False

LOCK_SIGNAL_GENERATION = "SIGNAL_GENERATION"
LOCK_PAIR_DISCOVERY = "PAIR_DISCOVERY"
LOCK_STATUS_UPDATE = "STATUS_UPDATE"
STATUS_UPDATE_LOCK_TTL_SECONDS = 10 * 60
SIGNAL_GENERATION_LOCK_TTL_SECONDS = 60 * 60
PAIR_DISCOVERY_LOCK_TTL_SECONDS = 60 * 60

SETTING_SIGNAL_GENERATION_PAUSED = "signal_generation_paused"
SETTING_PAIR_DISCOVERY_PAUSED = "pair_discovery_paused"
SETTING_STATUS_UPDATER_PAUSED = "status_updater_paused"
SETTING_TIER_3_ENABLED = "tier_3_enabled"
SETTING_ROLLOUT_MODE = "signal_pair_rollout_mode"
SETTING_MAX_SYMBOLS = "max_symbols"
SETTING_MAX_PUBLISHED_PER_SCAN = "max_published_per_scan"
SETTING_MIN_VOLUME = "min_volume"
SETTING_MAX_SPREAD = "max_spread"


def tiers_for_rollout_mode(mode: str | None) -> tuple[str, ...] | None:
    normalized = str(mode or DEFAULT_ROLLOUT_MODE).strip().upper()
    if normalized == ROLLOUT_TIER_1_ONLY:
        return ("TIER_1",)
    if normalized == ROLLOUT_TIER_1_TIER_2:
        return ("TIER_1", "TIER_2")
    if normalized == ROLLOUT_TIER_1_TIER_2_TIER_3:
        return ("TIER_1", "TIER_2", "TIER_3")
    return None

